AWSTemplateFormatVersion: "2010-09-09"
Description: pipeline

Parameters:
  ArtifactBucketName:
    Description: Production Account S3 Bucket Name for Artifact (Created by prepare.yaml)
    Type: String
  CmkArn:
    Description: Production Account CMK ARN (Created by prepare.yaml)
    Type: String
  CodePipelineRoleArn:
    Description: Production Account CodePipeline Service Role ARN (Created by prepare.yaml)
    Type: String
  CodeBiuldRoleArn:
    Description: Production Account CodeBuild Service Role ARN (Created by prepare.yaml)
    Type: String
  ActionRoleArn:
    Description: Repository Account CodeCommit Action Role ARN (Created by pipeline.yaml)
    Type: String
  RepositoryName:
    Type: String
    Description: CodeCommit repository name
  BranchName:
    Type: String
    Default: production
    AllowedValues:
      - production
  BuildSpecName:
    Type: String
    Description: buildspec file to executed by codebuild
  Runtime:
    Type: String
    Description: https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/runtime-versions.html
    Default: golang117
    AllowedValues: [golang116, golang117]
  NotifiArn:
    Type: String
    Description: destination chatbot arn for pipeline notifications
  PipelineName:
    Type: String
    Description: "${PipelineName}-${UUID}"

Mappings:
  # Runtimeに対応するイメージ名を列挙する
  BuildSetting:
    golang116:
      image: aws/codebuild/standard:5.0 # golang1.16 image
    golang117:
      image: XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/codebuild-custom-img:latest # カスタムイメージ

Resources:
  # CodePipeline
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Location: !Ref ArtifactBucketName
        Type: S3
        EncryptionKey:
          Id: !Ref CmkArn
          Type: KMS
      RoleArn: !Ref CodePipelineRoleArn
      RestartExecutionOnUpdate: false
      Name:
        Fn::Join:
          - "-"
          - - !Ref PipelineName
            - !Select [2, !Split ["/", !Ref AWS::StackId]]
      Stages:
        - Name: pull
          Actions:
            - Name: codecommit
              ActionTypeId:
                Category: Source
                Provider: CodeCommit
                Owner: AWS
                Version: 1
              Configuration:
                RepositoryName: !Ref RepositoryName
                BranchName: !Ref BranchName
                PollForSourceChanges: true
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
              RoleArn: !Ref ActionRoleArn
        - Name: run
          Actions:
            - Name: build
              ActionTypeId:
                Category: Build
                Provider: CodeBuild
                Owner: AWS
                Version: 1
              Configuration:
                ProjectName: !Ref BuildProject
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
  # CodeBuild
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !Ref CodeBiuldRoleArn
      Source:
        Type: CODEPIPELINE
        BuildSpec: !Ref BuildSpecName
      Artifacts: { Type: CODEPIPELINE }
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !FindInMap [BuildSetting, !Ref Runtime, image]
        ImagePullCredentialsType: SERVICE_ROLE
        Type: LINUX_CONTAINER
        PrivilegedMode: true
      TimeoutInMinutes: 30
      LogsConfig:
        CloudWatchLogs:
          GroupName:
            Fn::Join:
              - ""
              - - "/code-build/log/xxxxxx/" # TODO: よしなに
                - !Select [2, !Split ["/", !Ref AWS::StackId]]
          Status: ENABLED
  # CloudWatch
  CodeBuildLogWeb:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Join:
          - ""
          - - "/code-build/log/xxxxxx/" # TODO: よしなに
            - !Select [2, !Split ["/", !Ref AWS::StackId]]
      RetentionInDays: 30
  # Notification
  Notification:
    Type: AWS::CodeStarNotifications::NotificationRule
    Properties:
      DetailType: BASIC
      EventTypeIds:
        - codepipeline-pipeline-pipeline-execution-succeeded
        - codepipeline-pipeline-pipeline-execution-failed
      Name:
        Fn::Join:
          - "-"
          - - !Ref PipelineName
            - !Select [2, !Split ["/", !Ref AWS::StackId]]
      Resource:
        Fn::Join:
          - ":"
          - - "arn:aws:codepipeline"
            - !Ref AWS::Region
            - !Ref AWS::AccountId
            - !Ref Pipeline
      Status: ENABLED
      Targets:
        - TargetAddress: !Ref NotifiArn
          TargetType: AWSChatbotSlack
